name: Packer

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-10.15

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use latest Packer
        uses: hashicorp-contrib/setup-packer@v1

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install zx
        run: |
          npm i -g zx

      - name: Set up QEMU
        run: |
          brew install qemu

      - name: Install mc
        run: |
          brew install minio/stable/mc
          mc alias set wasabi https://s3.us-west-1.wasabisys.com ${{ secrets.S3_ACCESS_KEY }} ${{ secrets.S3_SECRET_KEY }}

      - name: Run prepare.sh
        run: |
          scripts/prepare.sh

      - name: Build images
        run: |
          echo "$SCRIPT" | zx
        env:
          SCRIPT: |
            import path from "path";
            const configs = (await $`find images -name "config.json"`)
              .stdout
              .split("\n")
              .filter(x => x !== "");

            const root = process.cwd();
            for (const c of configs) {
              const dir = (await $`dirname ${c}`).stdout.trim();
              cd(dir);
              await $`packer build ${path.relative(dir, c)}`;
              const general = JSON.parse(await fs.readFile(`${dir}/general.json`));
              await $`mc cp output-qemu/packer-qemu wasabi/qcow2/${general.name}`;

              cd(root);
            }
