name: Packer

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use latest Packer
        uses: hashicorp-contrib/setup-packer@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
