name: Packer

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-10.15

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use latest Packer
        uses: hashicorp-contrib/setup-packer@v1

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install zx
        run: |
          npm i -g zx

      - name: Set up QEMU
        run: |
          brew install qemu

      - name: Build images
        run: |
          echo "$SCRIPT" | zx
        env:
          SCRIPT: |
            const configs = (await $`find images -name "*.json"`)
              .stdout
              .split("\n")
              .filter(x => x !== "");

            for (const c of configs) {
              await $`packer build ${c}`
            }
